version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sweety912
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  backend:
    # image: nestjs-gql:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=mongodb
volumes:
  mongodb_data:
