version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=belstar123
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app/service/src
      - /app/service/src/node_modules
    env_file:
      - .env
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=mongodb
    command: "yarn start:dev"
volumes:
  mongodb_data:
